### ISSUE TITLE
Declaration of Statement::fetchAll not compatible with PDOStatement::fetchAll

### ISSUE THREAD

**Issue by mrakotomizao** [appsfortableau/laravel-pdo-odbc#4]
`[01-Mar-2022 12:01:36 UTC] PHP Fatal error:  Declaration of LaravelPdoOdbc\Flavours\Snowflake\PDO\Statement::fetchAll($how = PDO::FETCH_BOTH, $class_name = null, $ctor_args = null) must be compatible with PDOStatement::fetchAll(int $mode = PDO::FETCH_DEFAULT, mixed ...$args) in /opt/app/vendor/yoramdelangen/laravel-pdo-odbc/src/Flavours/Snowflake/PDO/Statement.php on line 104`

Error occured when discovering packages. 

Same error on Statement::fetch().

PHP version : 8.0.8
Composer : 2

**Comment by yoramdelangen** [comment]
Thank you for reporting! I think this has to do with the PHP8, but I'll look into it.
In the near future, I am going to update this package with Snowflake extension support.

**Comment by mrakotomizao** [comment]
we doesn't have the issue on php 7.4 but anther issue shows up :  https://github.com/yoramdelangen/laravel-pdo-odbc/issues/5

**Comment by yoramdelangen** [comment]
@mrakotomizao are you using the Snowflake driver as ODBC driver. What happens without specifying the ODBC driver and keeping it using the default driver?

**Comment by yoramdelangen** [comment]
In version 1.2 this will be fixed.

**Comment by yoramdelangen** [comment]
1.2 is still not out

**Comment by huzaifa-qidwai** [comment]
Declaration of LaravelPdoOdbc\Flavours\Snowflake\PDO\Statement::fetchAll($how = PDO::FETCH_BOTH, $class_name = null, $ctor_args = null) must be compatible with PDOStatement::fetchAll(int $mode = PDO::FETCH_DEFAULT, mixed ...$args)
  at vendor/yoramdelangen/laravel-pdo-odbc/src/Flavours/Snowflake/PDO/Statement.php:115
  On running 
  php artisan migrate:status

**Comment by mckaygerhard** [comment]
any news on that? seems only affect php 8 ?

**Comment by yoramdelangen** [comment]
Fixed in 1.2 version
