### ISSUE TITLE
Failed to install the package

### ISSUE THREAD

**Issue by basselhossam95** [appsfortableau/laravel-pdo-odbc#9]
when I try to install the package in my project I get this error
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yoramdelangen/laravel-pdo-odbc[1.1.0, ..., 1.1.5] require ext-odbc * -> it is missing from your system. Install or enable PHP's odbc extension.
    - Root composer.json requires yoramdelangen/laravel-pdo-odbc ^1.1 -> satisfiable by yoramdelangen/laravel-pdo-odbc[1.1.0, ..., 1.1.5].

To enable extensions, verify that they are enabled in your .ini files:
    - /Applications/MAMP/bin/php/php7.4.21/conf/php.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```
even though I have added snowflake_pdo.so to my php
![image](https://user-images.githubusercontent.com/96523755/171609389-3fe94df7-b9c0-4d23-abf3-fb021d1df763.png)
and when I installed it with `--ignore-platform-reqs` it worked so I suggest to revert this change https://github.com/yoramdelangen/laravel-pdo-odbc/commit/304c6a67a131d013c54a9d6b830877a2b5214a68 since someone can use the package with the native snowflake pdo driver

**Comment by yoramdelangen** [comment]
Originally the package is based upon the ODBC extension and you should have the ODBC extension installed as well.

```
ext-odbc * -> it is missing from your system.
```

Unfortunately, it is not possible to set optional extensions in composer

**Comment by yoramdelangen** [comment]
It is still optional to use the snowflake_pdo extension and what you suggesting is not backward compatible

**Comment by yoramdelangen** [comment]
I agree, will remove it in new version

**Comment by c00p3r** [comment]
> why it's not backward compatible since these extensions are not required so it make sense to remove them from the required extensions

Also voting for that
extensions should be optional
